# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
#  Books: books  # 豆瓣书单
  Links: links  # 友链
  About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home
  archives: icon-archive
  categories: icon-folder
  tags: icon-tag
  repository: icon-project
  books: icon-book
  links: icon-friend
  about: icon-cup

site:
  favicon: /images/favicon.ico
  #manifest:
  site_verification:
#    google:
#    baidu:
  google_analytics: G-GV9V3WK361
#  service_worker:

pagination:
  prev:
    alwayShow: true
  next:
    alwayShow: true

comment:
  type: gitalk  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  livere:
    uid: # enter youyan uid
  gitalk: # gitalk. https://gitalk.github.io/
    owner: zman-hz #必须. GitHub repository 所有者，可以是个人或者组织。
    admin: zman-hz #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo: zman-hz.github.io #必须. GitHub repository.
    ClientID: c7359a6732cadb4c7760 #必须. GitHub Application Client ID.
    ClientSecret: 10f342a32949cd260a8f2e56817d1b2c00d3ac18 #必须. GitHub Application Client `ecret.
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html


github:
  username: zman-hz

# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计

search: true # enable local search
toc: true
fancybox: true
license: 
footer: '本文有任何错误地方或者容易引起误解的地方，请留言斧正!(If there are any errors or misunderstandings in this article, please leave a comment!)'
#  custom:

profile:
  enabled: true # Whether to show profile bar
  avatar: /images/avatar.jpeg
  #gravatar: manzhzh@163.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Alex Man
  author_title: Java Developer & Desinger
  author_description: Don't just promise, Prove; Don't just dream, Do!
  location: Hangzhou, China
  follow: https://github.com/zman-hz
  # Social Links
  social:
    links:
      github: https://github.com/zman-hz
      telegram: 
      twitter: 
      # facebook: /
      # dribbble: /
#      behance: https://www.behance.net/cofess
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false

  # My Personal Links
  links:
    Github: https://github.com/zman-hz
    Blog: https://zman-hz.github.io/
    Email: manzhzh@163.com
    Wechat: ★★☆★★
  # My Personal Labels
  labels:
    - 后端
    - Java
    - Oracle
    - Spring
    - 前端
    - JavaScript
    - React
    - Vue
    - Node.js
    - MacOs
  skills:
    Git: ★★★★★☆
    Java: ★★★★★☆
    Oracel: ★★★★☆
    Javascript: ★★★☆☆☆
    React: ★★★☆☆☆
    HTML+CSS: ★★★☆☆☆
    Bootstrap: ★★★☆☆☆
   # My Personal Works
  works:
   name:
     link: https://zman-hz.github.io/
     date: since 2016
  # My Personal Projects
  projects:
    zman-hz/codedemo: https://github.com/ZMan-HZ/codedemo
    zman-hz/springbootdemos: https://github.com/ZMan-HZ/springbootdemos
    zman-hz/OracleOnMacOS: https://github.com/ZMan-HZ/OracleOnMacOS
    zman-hz/springboot-dubbo: https://github.com/ZMan-HZ/springboot-dubbo
    zman-hz/DevTools: https://github.com/ZMan-HZ/DevTools

widgets:
#  - board
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

#widget behaivor
show_count: true

cdn:
  katex: //cdn.jsdelivr.net/npm/katex@0.9.0/dist/katex.min.css
  gitment: //cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css
  gitalk: //cdn.jsdelivr.net/npm/gitalk@1.4.0/dist/gitalk.min.css
  gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1.5.2/dist/gitalk.min.js
  yox: //cdn.jsdelivr.net/npm/yox@1.0.0-alpha.121/dist/standard/prod/yox.min.js
  blueimp_md5: //cdn.jsdelivr.net/npm/blueimp-md5@2.10.0/js/md5.min.js
  valine: //cdn.jsdelivr.net/npm/valine@1.3.10/dist/Valine.min.js
  lightgallery_css: //cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/css/lightgallery.min.css
  lightgallery_js: //cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/js/lightgallery.min.js
